### ISSUE TITLE
Suggestions of some good books

### ISSUE THREAD

**Issue by Anirudh257** [mr-mig/booklist#2]
@mr-mig . Sir, this is a very knowledgeable and expansive repository. I want to suggest few books that are worth a good read. Feel free to add them.
Hackers and Painters(https://www.amazon.com/Hackers-Painters-Big-Ideas-Computer/dp/1449389554)
Mythical Man Month(https://www.amazon.com/Mythical-Man-Month-Software-Engineering-Anniversary/dp/0201835959/ref=pd_sim_14_8?_encoding=UTF8&psc=1&refRID=QRKBFB44K30D6M92TTQ7)

**Comment by mr-mig** [comment]
Thank you! Good addition. I will add those books.

**Comment by Anirudh257** [comment]
Your welcome, sir. Thank you for creating such a great repository.
